#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Chino.Android.Tests.Resource", IsApplication=true)]

namespace Chino.Android.Tests
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.CreditsButton = global::Chino.Android.Tests.Resource.Id.CreditsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Chino.Android.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Chino.Android.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Chino.Android.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Chino.Android.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Chino.Android.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Chino.Android.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Chino.Android.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Chino.Android.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Chino.Android.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Chino.Android.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Chino.Android.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Chino.Android.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Chino.Android.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Chino.Android.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Chino.Android.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Chino.Android.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunEverythingButton = global::Chino.Android.Tests.Resource.Id.RunEverythingButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Chino.Android.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Chino.Android.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Chino.Android.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Chino.Android.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.Runner = global::Chino.Android.Tests.Resource.Layout.Runner;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Chino.Android.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Chino.Android.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int CreditsButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int OptionHostName = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int OptionPort = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int OptionRemoteServer = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int OptionsButton = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int ResultFullName = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ResultMessage = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int ResultResultState = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int ResultRunSingleMethodTest = 2130837512;
			
			// aapt resource value: 0x7F02000A
			public const int ResultsFailed = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int ResultsId = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int ResultsIgnored = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int ResultsInconclusive = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int ResultsMessage = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int ResultsPassed = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int ResultsResult = 2130837520;
			
			// aapt resource value: 0x7F020009
			public const int ResultStackTrace = 2130837513;
			
			// aapt resource value: 0x7F020011
			public const int RunEverythingButton = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int RunTestsButton = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int TestSuiteListView = 2130837523;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Runner = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int test_result = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int test_suite = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher_foreground = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_round = 2130968578;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
