# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the ci branch
  push:
    branches: [ master, 'feature/**' ]
  pull_request:
    branches: [ master, 'feature/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        Configuration: [Debug, Release]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Select Xcode version
      run: |
        sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
        xcodebuild -version
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14.0 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-nuget-packages
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{ github.workspace }}/.nuget/packages
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.csproj') }}
    - name: Prepare
      run: |
        nuget restore
    # Build check Chino library
    - name: Android
      run: |
        msbuild ./Chino.Android/Chino.Android.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: iOS
      run: |
        msbuild ./Chino.iOS/Chino.iOS.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    # Build check Sample app
    - name: SampleCommon
      run: |
        msbuild ./Sample.Common/Sample.Common.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: SampleAndroid
      run: |
        msbuild ./Sample.Android/Sample.Android.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: SampleiOS
      run: |
        msbuild ./Sample.iOS/Sample.iOS.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
  test:
    runs-on: macos-latest
    needs: [build]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14.0 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-nuget-packages
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.csproj') }}
    - name: Prepare
      run: |
        nuget restore
    - name: Common.Tests
      run: |
        cd Chino.Common.Tests
        dotnet test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
  pack:
    runs-on: macos-latest
    needs: [test]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14.0 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-nuget-packages
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.csproj') }}
    - name: Prepare
      run: |
        nuget restore
    - name: Common
      run: |
        msbuild ./Chino.Common/Chino.Common.csproj /t:pack /p:Configuration=Release
    - name: Android
      run: |
        msbuild ./Chino.Android/Chino.Android.csproj /t:pack /p:Configuration=Release
    - name: iOS
      run: |
        msbuild ./Chino.iOS/Chino.iOS.csproj /t:pack /p:Configuration=Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget_packages
        path: ${{ github.workspace }}/**/bin/Release/*.nupkg
        retention-days: 90
