name: Release

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        Configuration: [Debug, Release]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-nuget-packages
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.csproj') }}
    - name: Prepare
      run: |
        nuget restore
    # Build check Chino library
    - name: Android
      run: |
        msbuild ./Chino.Android/Chino.Android.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: iOS
      run: |
        msbuild ./Chino.iOS/Chino.iOS.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    # Build check Sample app
    - name: SampleCommon
      run: |
        msbuild ./Sample.Common/Sample.Common.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: SampleAndroid
      run: |
        msbuild ./Sample.Android/Sample.Android.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: SampleiOS
      run: |
        msbuild ./Sample.iOS/Sample.iOS.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    # Test Chino.Common library
    - name: Common.Tests
      run: |
        cd Chino.Common.Tests
        dotnet test -c ${{ matrix.Configuration }}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
  pack:
    runs-on: macos-latest
    needs: [build]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-nuget-packages
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.csproj') }}
    - name: Prepare
      run: |
        nuget restore
    - name: Common
      run: |
        msbuild ./Chino.Common/Chino.Common.csproj /t:pack /p:Configuration=Release
    - name: Android
      run: |
        msbuild ./Chino.Android/Chino.Android.csproj /t:pack /p:Configuration=Release
    - name: iOS
      run: |
        msbuild ./Chino.iOS/Chino.iOS.csproj /t:pack /p:Configuration=Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget_packages
        path: ${{ github.workspace }}/**/bin/Release/*.nupkg
